language: julia
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required

addons:
  apt:
    packages:
      - doxygen

# Before anything else, get the latest versions of things  
before_script:
- julia --color=yes -e 'using Pkg; pkg"add BinaryBuilder"; pkg"precompile"'

script:
- julia --color=yes build_tarballs.jl

deploy:
  provider: releases
  api_key:
    secure: $DOCUMENTER_KEY
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: wookay/H3Builder
    tags: true
